### ISSUE TITLE
Empty source file in the clone report

### ISSUE THREAD

**Issue by Xiaoven** [CordyJ/Open-NiCad#4]
### Environment
- OS: Ubuntu 22.04.4 LTS
- NiCad Assets: [nicad-7.0.0-linux64.tar.gz](https://github.com/CordyJ/Open-NiCad/releases/download/v7.0.0/nicad-7.0.0-linux64.tar.gz)

### Description
While analyzing the `blocks-blind-crossclones-0.30.xml` generated by NiCad, I observed inconsistencies in the `file` field for certain clones. Specifically, some clone entries had an empty `file` field, as illustrated below:

```xml
<clone nlines="26" similarity="83">
<source file pcid="4810"></source>
<source file="nicadclones/project1/project2/src/main/java/AugEvalFunction.java" startline="224" pcid="27771"></source>
</clone>
```

#### Issue Encountered
1. **Error with rename-blind-report Configuration**:
When attempting to run NiCad with the rename-blind-report configuration (min line = 6), an error was encountered during the source file retrieval process. The error message indicated a failure to open the source file:
  ```sh
  ./bin/nicadcross blocks java path/project1 path/project2 rename-blind-report
  ```

  ```log
./lib/nicad/tools/getsource.x nicadclones/project1/project1_blocks-blind-crossclones/project1_blocks-blind-crossclones-0.30-classes.xml nicadclones/project1/project1_blocks-blind-crossclones/project1_blocks-blind-crossclones-0.30-classes-withsource.xml
nicadclones/project1/project1_blocks-blind-crossclones/project1_blocks-blind-crossclones-0.30-classes.xml
*** Error: can't open source file 

real    0m0.005s
user    0m0.001s
sys 0m0.000s
  ```
This error indicates a potential issue when encountering clones with an empty file field.

When executing NiCad with the rename-blind configuration, although the error was not thrown, the issue with empty file instances persisted. 

#### Input to Replicate the Issue
[input.zip](https://github.com/CordyJ/Open-NiCad/files/14859240/input.zip)

**Comment by CordyJ** [comment]
Thank you, this is an interesting issue.

**Comment by CordyJ** [comment]
Note to maintainer: java.grm width spec is 128.
