### ISSUE TITLE
Clarify `Install.sh` executable presence

### ISSUE THREAD

**Issue by viralpraxis** [CordyJ/Open-NiCad#7]
Documentation mentions than `Install.sh` should be invoked  in order to install nicad globally:

> 4. (Optional system installation option) To install NiCad permanently for 
>    everyone on the computer (for example, if you have a research group 
>    all working on the same compute server), use the command:
> 
>       sudo ./Install.sh 

But I only see `src/installer/InstallNicad.sh` executable which seem to installing nicad globally. So, am I doing something wrong or the docs are outdated?

**Comment by CordyJ** [comment]
Thanks for this. The documentation should say ```InstallNicad.sh```. If you don't install NiCad globally, you just run it in place.
